version: 1
image: runicos/base
pipeline:
  rand:
    capability: RAW
    args:
      length: 4
    outputs:
      - type: F32
        dimensions:
          - 1
          - 1
  mod360:
    proc-block: "hotg-ai/proc-blocks@v0.11.3#modulo"
    inputs:
      asdgf: rand
    outputs:
      - type: F32
        dimensions:
          - 1
          - 1
    args:
      modulus: 360.0
  sine:
    model: "./sinemodel.tflite"
    inputs:
      asdf: mod360
    outputs:
      - type: F32
        name: identity
        dimensions:
          - 1
          - 1
  serial:
    out: serial
    inputs:
      - sine
